package xin.allview.schoolcms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLClassificationnote<M extends BaseLClassificationnote<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}

	public java.lang.String getCreater() {
		return get("creater");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}

	public java.lang.String getCreatetime() {
		return get("createtime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setClassid(java.lang.Integer classid) {
		set("classid", classid);
	}

	public java.lang.Integer getClassid() {
		return get("classid");
	}

	public void setNoteid(java.lang.Integer noteid) {
		set("noteid", noteid);
	}

	public java.lang.Integer getNoteid() {
		return get("noteid");
	}

	public void setExpand(java.lang.String expand) {
		set("expand", expand);
	}

	public java.lang.String getExpand() {
		return get("expand");
	}

}
