package xin.allview.schoolcms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLRoleauthor<M extends BaseLRoleauthor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}

	public java.lang.String getCreatetime() {
		return get("createtime");
	}

	public void setRoleid(java.lang.Integer roleid) {
		set("roleid", roleid);
	}

	public java.lang.Integer getRoleid() {
		return get("roleid");
	}

	public void setAuthorid(java.lang.Integer authorid) {
		set("authorid", authorid);
	}

	public java.lang.Integer getAuthorid() {
		return get("authorid");
	}

}
