package xin.allview.schoolcms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassification<M extends BaseClassification<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}

	public java.lang.String getCreater() {
		return get("creater");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}

	public java.lang.String getCreatetime() {
		return get("createtime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}

	public java.lang.Integer getPid() {
		return get("pid");
	}

	public void setClassname(java.lang.String classname) {
		set("classname", classname);
	}

	public java.lang.String getClassname() {
		return get("classname");
	}

	public void setExpand(java.lang.String expand) {
		set("expand", expand);
	}

	public java.lang.String getExpand() {
		return get("expand");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

}
