package xin.allview.schoolcms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNote<M extends BaseNote<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreater(java.lang.String creater) {
		set("creater", creater);
	}

	public java.lang.String getCreater() {
		return get("creater");
	}

	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}

	public java.lang.String getCreatetime() {
		return get("createtime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setExpand(java.lang.String expand) {
		set("expand", expand);
	}

	public java.lang.String getExpand() {
		return get("expand");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContext(java.lang.String context) {
		set("context", context);
	}

	public java.lang.String getContext() {
		return get("context");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setHobby(java.lang.String hobby) {
		set("hobby", hobby);
	}

	public java.lang.String getHobby() {
		return get("hobby");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

}
