package xin.allview.schoolcms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLUpesnuserrole<M extends BaseLUpesnuserrole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoleid(java.lang.Integer roleid) {
		set("roleid", roleid);
	}

	public java.lang.Integer getRoleid() {
		return get("roleid");
	}

	public void setUpesnuserid(java.lang.Integer upesnuserid) {
		set("upesnuserid", upesnuserid);
	}

	public java.lang.Integer getUpesnuserid() {
		return get("upesnuserid");
	}

}
