package xin.allview.schoolcms.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import xin.allview.schoolcms.model.base.BaseUserClassification;
import xin.allview.utils.Uitls;


import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class L_userClassification extends BaseUserClassification<L_userClassification> {
	public static final L_userClassification dao = new L_userClassification().dao();



	public List<L_userClassification> findConactByUserId(int userId){
		String sql="select l.* ,t.classname,t.img from l_userclassification l LEFT JOIN t_classification t on l.classificationid=t.id where l.creater =? order by l.createtime";
		List<L_userClassification> list= L_userClassification.dao.find(sql,userId);
		return list;
	}

}
