package xin.allview.schoolcms.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import xin.allview.utils.Uitls;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class T_reply extends Model<T_reply> {
	public static final T_reply dao = new T_reply();

	/**
	 * peng
	 * @param noteId
	 * @param userId
	 * @param context
     * @return
     */
	public boolean addReply(int noteId,int userId,String context){
		T_reply tr=new T_reply();
		tr.set("creater",userId);
		Date date=new Date();
		/*SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		String time=format.format(date);*/
		tr.set("create_time", Uitls.currTime());
		tr.set("version",1);
		tr.set("reply_context",context);
		tr.set("reply_note",noteId);
		boolean flag =tr.save();
		return flag;
	}

	/**
	 * peng
	 * @param page
	 * @param pageSize
	 * @param noteId
     * @return
     */
	public Page<Record> findReply(int page,int pageSize,int noteId){
		String sql="select r.*,u.nick_name ";
		String sql1="from t_reply r LEFT JOIN l_user u on r.creater =u.id where r.reply_note =? order by r.create_time DESC";
		Page<Record> pageList=null;
		try {
		 pageList= Db.paginate(page,pageSize,sql,sql1,noteId);
		}catch (Exception e){
			e.printStackTrace();
		}
		return  pageList;
	}

	/**
	 * 获取一条回复详情
	 * KLP
	 */
	public T_reply findReplyByReplyId(int replyId){
		String sql = "select * from t_reply where id = "+replyId;
		T_reply t_reply = T_reply.dao.findFirst(sql);
		return t_reply;

	}

	/**
	 *
	 *   添加拆解工作
	 *   	-- created by Samous
	 *
	 * @param note
	 * @param userid
	 * @param content
	 * @param people
	 * @return
	 */
	public boolean addAssignedReply(Integer note, int userid, String content, Integer[] people) {

		//将数组转为字符串保存
		String ids = "";
		for (int i = 0; i < people.length - 1; i++) {
			ids += people[i] + ",";
		}

		ids += people[people.length - 1];

		T_reply tr=new T_reply();
		tr.set("creater",userid);
		Date date=new Date();
		/*SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		String time=format.format(date);*/
		tr.set("create_time", Uitls.currTime());
		tr.set("version",1);
		tr.set("reply_context",content);
		tr.set("reply_note",note);
		tr.set("expand", "{\"people\":\"" + ids + "\"}");

		boolean flag =tr.save();
		return flag;

	}
}
